package com.imfibit.activitytracker.core

object TestTag {

    const val ACTIVITY_RECORD = "ACTIVITY_RECORD";
    const val MONTH_GRID_TODAY = "MONTH_GRID_TODAY";
    const val MONTH_GRID_DATE = "MONTH_GRID_TODAY_";

    const val GENERAL_BACK_BUTTON = "GENERAL_BACK_BUTTON"
    const val ONBOARDING_SKIP = "ONBOARDING_SKIP"
    const val ONBOARDING_PAGE = "ONBOARDING_PAGE_"
    const val ONBOARDING_PAGE_GO_TO_APP = "ONBOARDING_PAGE_GO_TO_APP"


    const val DASHBOARD_ADD_ACTIVITY = "DASHBOARD_ADD_ACTIVITY"
    const val DASHBOARD_ACTIVITIES_CONTENT = "DASHBOARD_ACTIVITIES_CONTENT"
    const val DIALOG_ADD_ACTIVITY_TIME = "DIALOG_ADD_ACTIVITY_TIME"
    const val DIALOG_ADD_ACTIVITY_SCORE = "DIALOG_ADD_ACTIVITY_SCORE"
    const val DIALOG_ADD_ACTIVITY_COMPLETION = "DIALOG_ADD_ACTIVITY_COMPLETION"
    const val DIALOG_ADD_ACTIVITY_FOCUS_ITEM = "DIALOG_ADD_ACTIVITY_FOCUS_ITEM"
    const val DIALOG_ADD_ACTIVITY_GROUP = "DIALOG_ADD_ACTIVITY_GROUP"
    const val TRACKED_ACTIVITY_SCREEN = "TRACKED_ACTIVITY_SCREEN"
    const val TRACKED_ACTIVITY_EDIT_NAME = "TRACKED_ACTIVITY_EDIT_NAME"
    const val TRACKED_ACTIVITY_ACTION_BUTTON = "TRACKED_ACTIVITY_ACTION_BUTTON"
    const val TRACKED_ACTIVITY_TIME_CLOSE_SESSION = "TRACKED_ACTIVITY_TIME_CLOSE_SESSION"



}